### ISSUE TITLE
Code injection via insecure download URL

### ISSUE THREAD

**Issue by jpstotz** [bruderstein/npp-plugins-x64#114]
I noticed that a lot of plugins in the `plugins64.xml` are using an insecure HTTP:// link as download source. 

Are you aware that this effectively means that an attacker can intercept such downloads and modify/replace  the downloaded file - this means an attacker can place arbitrary code on the computer of the user that is downloading the plugin while the attack is in progress.

Hence an attacker could install trojans, or back-door software. As a conclusion using the Notepad++ with plugin manager is currently a security risk.

Therefore IMHO you should set a policy that at least the <download> URLs have to be TLS protected (HTTPS://) to be accepted. The best would be to only accept HTTPS links in any xml element (<download>, <homepage>, <sourceUrl>).

**Comment by chcg** [comment]
@jpstotz Why a lot? I just found:

Line 928: 				<download>http://www.architectshack.com/GetFile.aspx?File=SqlFormatterNppPlugin.x64.1.6.10.zip&amp;Page=PoorMansTSqlFormatter</download>
	Line 1084: 				<download>http://www.sqlinform.com/npp/SQLinFormNpp64_5.3.19.zip</download>
	Line 1174: 				<download>http://phdesign.com.au/assets/files/NppToolBucket-1.10-x64.zip</download>

and changed them to https except of http://www.architectshack.com which is not accessible via https.

**Comment by jpstotz** [comment]
OK, considering only the download links it is more a "some" than "a lot". Anyway one insecure URL can be enough to compromise a users computer.

What to you think about the HTTPS only policy? If you disagree at least there should be IMHO a security warning from the plugin manager to the user before downloading a plugin via an insecure connection.

Are there any plans to support code signing? That would be correct way for a plugin manager to verify that a download has not been altered. The used code signing public key could then be placed in the `plugins64.xml` file.

**Comment by dinkumoil** [comment]
@chcg I tested to download all plugins above via HTTPS. The download of SqlFormatterNppPlugin.x64.1.6.10.zip failed, the server seems not to be HTTPS aware.

**Comment by chcg** [comment]
For x64 the https only policy could make sense as these plugins are quite new and actively maintained. For the older x86 Unicode or even ANSI plugins that is more problematic to achieve without breaking the support, I think.

There is a md5 sum on modification of the download list, see https://github.com/bruderstein/npp-plugins-x64/blob/master/plugins/validate.json. In case the implementer has created a pull request he has calculated that sum and via the github account the user could be verified.

**Comment by jpstotz** [comment]
> For x64 the https only policy could make sense as these plugins are quite new and actively maintained.

That would be really a good improvement.

> There is a md5 sum on modification of the download list

MD5 is only useful for detecting accidental data changes. AFAIK the first collision attack on MD5 was successful in 1996. Even SHA-1 is considered [broken](https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html) from a security perspective (even though the effort for breaking it was very high. 

I assume that currently only MD5 can be used in the validate.json right? Therefore for future security enhancements it would be good if the plugin manager could handle also SHA-1 and SHA-256 hashes in this file. As each hash has a different length they are easily distinguishable from each other.

Some months after publishing the plugin manager version that can handle MD5, SHA-1 and SHA-256 hashes you could then change the policy for accepting validate.json pull requests that at least a SHA-1, better a SHA-256 hash has to be included.

**Comment by chcg** [comment]
@jpstotz I'm aware of the md5 collision problem, but as PM might have a limited lifetime due to https://notepad-plus-plus.org/community/topic/16494/new-built-in-plugin-admin-plugin-manager-is-ready
the interest to change this is somehow limited. 

Adding SHA-256 hashes to the json is not sufficient. The hashes need to be calculated from the local file and the webservice for PM need to support the check for SHA-256. 
Could you advise a good SHA-256 C\C++-implementation and a corresponding shell application?

**Comment by TaoK** [comment]
I'm missing something here - doesn't the plugin manager itself verify hashes of downloaded plugin files, on the user's computer, after download of the plugin archive?

I'm the owner of the http://www.architectshack.com plugin (Poor Man's T-Sql Formatter) and I'm happy to make files available over HTTPS - in fact, I just did for the new Plugin Admin system, which was for some reason having trouble with the current/old server - but this is the first time I hear of a need (via https://github.com/TaoK/PoorMansTSqlFormatter/issues/207 ).

If someone wants to update the Plugin Manager plugin list with the new download locations (AND new ZIP binaries, with new hashes - but the contents of the ZIP files are unchanged wrt previous v1.6.10), they are:

* https://github.com/TaoK/PoorMansTSqlFormatter/releases/download/1.6.10/SqlFormatterNppPlugin.1.6.10.b.zip
* https://github.com/TaoK/PoorMansTSqlFormatter/releases/download/1.6.10/SqlFormatterNppPlugin.x64.1.6.10.b.zip

**Comment by TaoK** [comment]
Never mind my first comment - I see the real concern is with MD5... Personally, I think this is a little silly/paranoid; forging content (at reasonable data lengths) to have a specific MD5 hash value is, to the best of my knowledge, still impossible (not just expensive) in real-life practical terms. Finding *accidental* collisions is trivial these days - but I'm not sure how that's relevant.

UPDATE: having idly browsed a bit, I see that MD5 *collision* and *targeted collision* attacks are entirely feasible, but practical/useful *preimage* attacks, the ones that apply here, are not known at this time. I am of course not suggesting MD5 should ever be actively **chosen** for security applications - just claiming that Plugin Manager's use of MD5, at this time, does not warrant realistic concern. 

As @chcg has pointed out, Plugin Manager is likely to become a historical anecdote in the not-too-distant future in the face of Plugin Admin infrastructure in Notepad++ 7.6 and later - so it probably doesn't make sense to expend any effort on fixing this not-currently-practical vulnerability.

I'd love to see any evidence to the contrary, however!

**Comment by chcg** [comment]
@TaoK Indeed https://en.wikipedia.org/wiki/MD5#Preimage_vulnerability is not practical, but maybe already a collision could lead to a useable attack, if the dll is modified to crash N++. So it isn't a bad idea nowadays to raise the hurdle for a malicious attacker before issues are known.

**Comment by chcg** [comment]
All download locations switched to https now . Just some homepage locations remain.
