### ISSUE TITLE
Add a column for plugin release date

### ISSUE THREAD

**Issue by kenijo** [bruderstein/npp-plugins-x64#117]
The idea is to be able to sort by release date to know which are the newer plugins that are released.

**Comment by chcg** [comment]
@kenijo See https://github.com/bruderstein/nppPluginManager/issues/29, support needs to be added to the PM itself, it is not sufficient to add that information just to the list. Currently this information is partly available by the entry <latestUpdate>, e.g.
https://github.com/bruderstein/npp-plugins-x64/blob/master/plugins/plugins64.xml#L12
