### ISSUE TITLE
[Question] Behavior of backup="true"

### ISSUE THREAD

**Issue by dail8859** [bruderstein/npp-plugins-x64#17]
I have a plugin that has ~130 files that I need to copy. It is possible the user may edit these files. When the plugin is updated I'd like to make sure the edited files don't get lost. I see using `backup="true"` will create a backup if the destination file exists. 

Would this *always* cause 130 backup files to be created? Or would only the files that have been changed get backed up?

**Comment by bruderstein** [comment]
It doesn't check the contents, if it exists, it renames it with a backup name.

I'd suggest doing something like a `default` folder, and then user changes in a separate directory.

Feel free to raise an issue and we can look into supporting checking the content (not sure how it would work though, you don't want to set the users changes back to default, but also want to update newer files that have changed in the update - what would we compare the contents too in this case?)

**Comment by dail8859** [comment]
> It doesn't check the contents, if it exists, it renames it with a backup name.

Ok, I figured this was the case but wanted to make sure.

> I'd suggest doing something like a `default` folder

This would be my solution as well however my plugin uses a 3rd party library that doesn't support this at all :( I still may be able to some file manipulation behind the scenes to make it work as expected.

> not sure how it would work though

Yeah I wasn't suggesting distinguishing between file changes due to user or due to plugin updates...this would probably be non-trivial. Just simply that if the file exists *and* the contents are different, then create the backup.

For now I'm fine with the way it works, just wanted some clarification. Thanks!
