### ISSUE TITLE
Sorry to hear about removal of plugin manager

### ISSUE THREAD

**Issue by ghost** [bruderstein/npp-plugins-x64#30]
I think the NPP author is being an ass - I have no problems with a small advert like their currently is.
Very disappointed and I hope enough people will complain to him to get your plugin manager re-instated.

**Comment by bruderstein** [comment]
Thanks for the words of support - that means a lot.  I can understand the opinion, even if I don't agree with it.  I think the plan at the moment is to keep it going until there is an alternative built into N++, then withdraw the service. Having multiple plugin management systems is not good for the community, and even more burdensome on the plugin authors.
