### ISSUE TITLE
Post for the forum

### ISSUE THREAD

**Issue by bruderstein** [bruderstein/npp-plugins-x64#4]
This is the post I've come up to post in the Plugin Development forum. Feedback / corrections / alterations welcome

/cc @chcg

---
This has been a long time coming, but thanks to @chcg there is now a x64 version of the plugin manager.

Download it the `_x64` variant from https://github.com/bruderstein/nppPluginManager/releases and copy the contents of the zip into the Notepad++ folder.

We've been holding back as we didn't have a way to administer the list of plugins for x64 - the current admin system doesn't deal with it, and we're working on a new implementation that does. However, this new admin system is taking a while, so we have an intermediate measure.

Don Ho is looking to replace the plugin manager with a built-in system with a list managed in git. So, in order to get the x64 variant of Plugin Manager released quicker, and to validate if plugin developers and the community will maintain the list, we have setup a repository hosting the list of x64 plugins.

### What this means for plugin developers?
For x86 (32bit) plugins, keep maintaining your plugin in the normal [admin system](https://npppm.bruderste.in/welcome).

For x64 plugins (and the x64 variants of x86 plugins), add your plugin via PR to the [plugin list repo](https://github.com/bruderstein/npp-plugins-x64).

### How to list a plugin?
Head over to https://github.com/bruderstein/npp-plugins-x64, fork the repo and create a PR with the changes. As soon as the PR is merged, within a few minutes the "development" plugin list is updated (enable using the development plugin list with the option in plugin manager settings).  For now, we'll update the production list from the development list every 24 hours.

### Can I add a plugin I don't own?
Yes, absolutely. We need all the help we can get to list all the available x64 plugins.

### Why isn't XXX plugin listed?
Each plugin needs to be added separately, we've only added the ones that come with Notepad++ to start off with, but we're hoping that plugin authors and community members will help fill out this list.  Please help us by contributing the plugin that is not listed.

### Is the admin system going away?
In it's current form, yes. The [new version](https://github.com/bruderstein/npppm), probably not. If the community prefers administering the plugin list with git, then we may well consider it. However, work will continue on the new admin system unless we reach a point where it's not considered useful.

### I'm a web developer, I'd like to help with the new admin system
Great! It's React, Node and Hapi, backed by CouchDB, you'll love it. Head over to https://github.com/bruderstein/npppm3 and take a look at the issues -they're labelled up with difficulties and what is necessary for the first version. We're really excited to see contributions to this project!

**Comment by chcg** [comment]
Just added the link to the current admin system, otherwise im fine with it.

**Comment by bruderstein** [comment]
Do we need to solve anything with the docs or validation from #2 first?
