### ISSUE TITLE
Two entries for AnalysePlugin in validate.json

### ISSUE THREAD

**Issue by dail8859** [bruderstein/npp-plugins-x64#63]
The validate.json file currently has two entries for AnalysePlugin with different hashes for the DLL file.

See 

https://github.com/bruderstein/npp-plugins-x64/blob/74ca36f3911cd2e977560fbea7f48b031152cfb4/plugins/validate.json#L20-L22

and

https://github.com/bruderstein/npp-plugins-x64/blob/74ca36f3911cd2e977560fbea7f48b031152cfb4/plugins/validate.json#L192-L195

**Comment by chcg** [comment]
thanks for this finding, fixed with https://github.com/bruderstein/npp-plugins-x64/commit/616157d1ebb090358a9ac7db5c9899bdcbceaa30
