### ISSUE TITLE
Can't Validate Integrity of MarkdownViewerPlusPlus

### ISSUE THREAD

**Issue by okonomiyaki3000** [bruderstein/npp-plugins-x64#94]
I also posted this here: nea/MarkdownViewerPlusPlus#77

Basically, a dll's integrity could be validated so completing the installation is not recommended. I haven't had this issue installing other plugins.

**Comment by chcg** [comment]
Fix uppercase\lowercase issue with MD5 sum. Fix is currently just available with the development plugin list. The transfer to the normal list will happen automatically within the next days.
